name: 'test-every-push'
on: push
jobs:
  build:
    name: Spring Boot Build
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: jdk 17 다운로드
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: gradlew 권한 부여
        run: chmod +x gradlew
      - name: 테스트
        run: ./gradlew test
      - name: 빌드
        run: ./gradlew build -x test
      - name: 이미지 만들기
        run: ./gradlew bootBuildImage --imageName=$DOCKERHUB_USERNAME/test1
      - name: 도커 허브 로그인
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: 이미지 푸시
        run: docker push $DOCKERHUB_USERNAME/test1
